### ISSUE TITLE
Незначительные правки оформления

### ISSUE THREAD

**Issue by redb0** [ananastyaa/various-optimization-algorithms#1]
# Правки оформления

Здесь приведены моменты, учет которых, возможно, позволит повысить качество кода или улучшить общее оформление.

## Модуль `hook_jeeves.py`

- Добавить в документацию функции `hook_jeeves` ссылку на описание метода в других источниках, например, в вики.
- Добавить в документацию функции `hook_jeeves` краткое описание метода, 2-3 предложения.
- В документацию функции `hook_jeeves` указать возможные границы параметров, если они нужны. Например, аргумент `lamb` должен лежать в каких пределах? Можно просто указать что он должен быть больше 0.
- В функции `hook_jeeves` нужно дополнить аннотацию для аргумента `function`. В `Callable` нужно указывать типы аргументов и возвращаемого значения функции. 
    - Документация `typing`: https://docs.python.org/3/library/typing.html#callable
    - Документация `mypy`: https://mypy.readthedocs.io/en/stable/cheat_sheet_py3.html#functions
- Добавить файл `__init__.py`

## Модуль `func.py`

- Привести имена всех функций в единый вид, например, `test_func_1`, `test_func_2` и тд.
- В документации к каждой функции нужно указать в каких координатах находится минимум и его значение
- Если используется стиль `reStructuredText` для оформления документации, то можно добавить формулу в формате `LaTeX`. Вопрос на stackoverflow: https://stackoverflow.com/questions/3610551/math-in-restructuredtext-with-latex.
- Что бы не обращаться постоянно по индексам можно воспользоваться распаковкой.
- Привести импорты в соответствие правилам
- Добавить файл `__init__.py`
- В модуле `__init__.py` через звездочку импортировать все функции из `func.py`. Это позволит писать не так `from test_functions.func import math_function`, а короче и удобнее `from test_functions import math_function`

## Модуль `graph.py`

- Добавить файл `__init__.py`
- Те же замечания к аннотациям с `Callable`
- Лишний отступ в документации к функции `graph_near_min`
- Можно не передавать массивы точек для `x` и `y` в функции `graph`, а возложить их генерацию на саму функцию. Для этого придется передавать левую и правую границу, например, в виде аргументов `xlim` и `ylim`, которые будут принимать кортеж из двух значений: левой и правой границы.

**Comment by ananastyaa** [comment]
Так точно сенсей, все исправлено :)

**Comment by redb0** [comment]
А где указание, что коммиты относятся к этому issue?

**Comment by redb0** [comment]
Так как все исправлено, закрываю
